apiVersion: v1
kind: Deployment
metadata:
  name: myapp-backend-pod
  labels:
    app: myapp-backend
spec:
  containers:
    - name: myapp-container
      image: sekarfeb/employee_backend:latest
      ports:
        - containerPort: 8080
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: myapp-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer # Use the appropriate service type for your environment
