apiVersion: v1
kind: Pod
metadata:
  name: myapp_backend-pod
  labels:
    app: myapp
spec:
  containers:
    - name: myapp-container
      image: sekarfeb/employee_backend:latest
      ports:
        - containerPort: 8080
